// @ts-check
/** @typedef {import("eslint").Linter.Config} EslintConfig */

import {
    asEslintPlugin,
    comments,
    eslintPluginCommentLength,
    eslintPluginEslintPlugin,
    eslintPluginMath,
    eslintPluginNoUseExtendNative,
    eslintPluginUnicorn,
    globals,
    importX,
    js,
    jsdocPlugin,
    listeners,
    moduleInterop,
    nodePlugin,
    perfectionist,
    pluginCanonical,
    pluginJSDoc,
    pluginNFDAR,
    pluginPromise,
    pluginRedos,
    pluginRegexLook,
    pluginRegexp,
    pluginSecurity,
    pluginUnusedImports,
    repositoryRootPath,
    sonarjs,
    sonarjsConfigs,
    tsdocRequire,
    tseslint,
    tseslintParser,
} from "./shared.mjs";

/** @type {EslintConfig[]} */
export const sourceConfigs = [
    // ═══════════════════════════════════════════════════════════════════════════════
    // #region 🔌 ESLint Plugin config
    // ═══════════════════════════════════════════════════════════════════════════════
    // SECTION: ESLint Plugin config
    // ═══════════════════════════════════════════════════════════════════════════════
    {
        files: [
            "*.{js,mjs,cjs,ts,mts,cts,tsx}",
            "src/**/*.{js,mjs,cjs,ts,mts,cts,tsx}",
            "eslint/config/**/*.{js,mjs,cjs,ts,mts,cts,tsx}",
            "test/**/*.{js,mjs,cjs,ts,mts,cts,tsx}",
            "benchmarks/**/*.{js,mjs,cjs,ts,mts,cts,tsx}",
        ],
        ignores: ["**/*.d.{ts,mts,cts}", "dist/**"],
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
                document: "readonly",
                globalThis: "readonly",
                window: "readonly",
            },
            parser: tseslintParser,
            parserOptions: {
                ecmaFeatures: {
                    impliedStrict: true,
                },
                ecmaVersion: "latest",
                jsDocParsingMode: "all",
                project: ["./tsconfig.eslint.json"],
                sourceType: "module",
                tsconfigRootDir: repositoryRootPath,
                warnOnUnsupportedTypeScriptVersion: true,
            },
        },
        name: "ESLint Plugin Source Files - project/**/*.*",
        plugins:
            /** @type {Record<string, import("eslint").ESLint.Plugin>} */ ({
                "@typescript-eslint": asEslintPlugin(tseslint),
                canonical: asEslintPlugin(pluginCanonical),
                "comment-length": eslintPluginCommentLength,
                "eslint-comments": asEslintPlugin(comments),
                "eslint-plugin": asEslintPlugin(eslintPluginEslintPlugin),
                "import-x": importX,
                js: js,
                jsdoc: jsdocPlugin,
                listeners: asEslintPlugin(listeners),
                math: asEslintPlugin(eslintPluginMath),
                "module-interop": asEslintPlugin(moduleInterop),
                n: nodePlugin,
                "no-function-declare-after-return": asEslintPlugin(pluginNFDAR),
                "no-lookahead-lookbehind-regexp":
                    asEslintPlugin(pluginRegexLook),
                "no-use-extend-native": asEslintPlugin(
                    eslintPluginNoUseExtendNative
                ),
                perfectionist: perfectionist,
                promise: asEslintPlugin(pluginPromise),
                redos: asEslintPlugin(pluginRedos),
                regexp: asEslintPlugin(pluginRegexp),
                "require-jsdoc": asEslintPlugin(pluginJSDoc),
                security: pluginSecurity,
                sonarjs: asEslintPlugin(sonarjs),
                "tsdoc-require-2": tsdocRequire,
                unicorn: eslintPluginUnicorn,
                "unused-imports": pluginUnusedImports,
            }),
        rules: {
            // TypeScript backend rules
            ...js.configs.all.rules,
            ...tseslint.configs["recommendedTypeChecked"],
            ...tseslint.configs["recommended"]?.rules,
            ...tseslint.configs["strictTypeChecked"],
            ...tseslint.configs["strict"]?.rules,
            ...tseslint.configs["stylisticTypeChecked"],
            ...tseslint.configs["stylistic"]?.rules,
            ...pluginRegexp.configs.all.rules,
            ...importX.flatConfigs.recommended.rules,
            ...importX.flatConfigs.electron.rules,
            ...importX.flatConfigs.typescript.rules,
            ...pluginPromise.configs["flat/recommended"].rules,
            ...eslintPluginUnicorn.configs.all.rules,
            ...sonarjsConfigs.recommended.rules,
            ...perfectionist.configs["recommended-natural"].rules,
            ...pluginSecurity.configs.recommended.rules,
            ...nodePlugin.configs["flat/all"].rules,
            ...eslintPluginMath.configs.recommended.rules,
            ...comments.recommended.rules,
            ...pluginCanonical.configs.recommended.rules,
            ...eslintPluginNoUseExtendNative.configs.recommended.rules,
            ...listeners.configs.strict?.rules,
            ...moduleInterop.configs.recommended.rules,

            "@eslint-community/eslint-comments/no-restricted-disable": "warn",
            // Deprecated rule - turned off
            "@eslint-community/eslint-comments/no-unused-disable": "off",
            "@eslint-community/eslint-comments/no-use": "off",
            "@eslint-community/eslint-comments/require-description": "warn",
            "@typescript-eslint/await-thenable": "error", // Prevent awaiting non-promises
            "@typescript-eslint/ban-ts-comment": "warn",
            "@typescript-eslint/ban-tslint-comment": "warn",
            "@typescript-eslint/class-literal-property-style": "warn",
            "@typescript-eslint/class-methods-use-this": "warn",
            "@typescript-eslint/consistent-generic-constructors": "warn",
            "@typescript-eslint/consistent-indexed-object-style": "warn",
            "@typescript-eslint/consistent-return": "warn",
            // Function and type safety rules
            "@typescript-eslint/consistent-type-assertions": "error",
            "@typescript-eslint/consistent-type-definitions": "warn",
            "@typescript-eslint/consistent-type-exports": "warn",
            "@typescript-eslint/consistent-type-imports": "warn",
            "@typescript-eslint/default-param-last": "warn",
            "@typescript-eslint/dot-notation": [
                "warn",
                {
                    allowPattern: "^[A-Z0-9_]+$",
                },
            ],
            "@typescript-eslint/explicit-function-return-type": [
                "warn",
                {
                    allowConciseArrowFunctionExpressionsStartingWithVoid: false,
                    allowDirectConstAssertionInArrowFunctions: true,
                    allowedNames: [],
                    allowExpressions: false,
                    allowFunctionsWithoutTypeParameters: false,
                    allowHigherOrderFunctions: true,
                    allowIIFEs: false,
                    allowTypedFunctionExpressions: true,
                },
            ],
            "@typescript-eslint/explicit-member-accessibility": "warn",
            "@typescript-eslint/explicit-module-boundary-types": "warn",
            "@typescript-eslint/init-declarations": "warn",
            "@typescript-eslint/max-params": [
                "warn",
                {
                    countVoidThis: false,
                    max: 20,
                },
            ],
            "@typescript-eslint/member-ordering": "warn",
            "@typescript-eslint/method-signature-style": "warn",
            "@typescript-eslint/naming-convention": "off",
            "@typescript-eslint/no-array-constructor": "warn",
            "@typescript-eslint/no-array-delete": "warn",
            "@typescript-eslint/no-base-to-string": "warn",
            "@typescript-eslint/no-confusing-non-null-assertion": "warn",
            "@typescript-eslint/no-confusing-void-expression": "warn",
            "@typescript-eslint/no-deprecated": "error",
            "@typescript-eslint/no-dupe-class-members": "warn",
            "@typescript-eslint/no-duplicate-enum-values": "warn",
            "@typescript-eslint/no-duplicate-type-constituents": "warn",
            "@typescript-eslint/no-dynamic-delete": "warn",
            "@typescript-eslint/no-empty-function": [
                "error",
                {
                    allow: ["arrowFunctions"], // Allow empty arrow functions for React useEffect cleanup
                },
            ],
            "@typescript-eslint/no-empty-object-type": "error",
            // Disable overly strict rules for this project
            "@typescript-eslint/no-explicit-any": "warn", // Sometimes needed
            "@typescript-eslint/no-extra-non-null-assertion": "warn",
            "@typescript-eslint/no-extraneous-class": "warn",
            // Advanced type-checked rules for async safety and runtime error prevention
            "@typescript-eslint/no-floating-promises": [
                "error",
                {
                    ignoreIIFE: false, // Catch floating IIFEs which can cause issues
                    ignoreVoid: true, // Allow void for intentionally ignored promises
                },
            ],
            "@typescript-eslint/no-for-in-array": "warn",
            "@typescript-eslint/no-implied-eval": "warn",
            // Keep enabled: Helps with bundle optimization and makes type vs runtime imports clearer.
            // Can be resolved incrementally as warnings.
            "@typescript-eslint/no-import-type-side-effects": "warn",
            "@typescript-eslint/no-inferrable-types": "warn", // Allow explicit types for React components
            "@typescript-eslint/no-invalid-this": "warn",
            "@typescript-eslint/no-invalid-void-type": "warn",
            "@typescript-eslint/no-loop-func": "warn",
            "@typescript-eslint/no-magic-numbers": "off",
            "@typescript-eslint/no-meaningless-void-operator": "warn",
            "@typescript-eslint/no-misused-new": "warn",
            "@typescript-eslint/no-misused-promises": [
                "error",
                {
                    checksConditionals: true, // Check if Promises used in conditionals
                    checksSpreads: true, // Check Promise spreads
                    checksVoidReturn: true, // Critical for IPC handlers
                },
            ],
            "@typescript-eslint/no-misused-spread": "warn",
            "@typescript-eslint/no-mixed-enums": "warn",
            "@typescript-eslint/no-namespace": "warn",
            "@typescript-eslint/no-non-null-asserted-nullish-coalescing":
                "warn",
            "@typescript-eslint/no-non-null-asserted-optional-chain": "warn",
            "@typescript-eslint/no-non-null-assertion": "warn", // Zustand patterns
            "@typescript-eslint/no-redeclare": "warn",
            "@typescript-eslint/no-redundant-type-constituents": "warn",
            "@typescript-eslint/no-require-imports": "warn",
            // Granular selector rules still need to be added manually here.
            "@typescript-eslint/no-restricted-imports": "warn",
            "@typescript-eslint/no-restricted-types": [
                "error",
                {
                    types: {
                        Function: {
                            message: [
                                "The `Function` type accepts any function-like value.",
                                "It provides no type safety when calling the function, which can be a common source of bugs.",
                                "If you are expecting the function to accept certain arguments, you should explicitly define the function shape.",
                                "Use '(...args: unknown[]) => unknown' for generic handlers or define specific function signatures.",
                            ].join("\n"),
                        },
                    },
                },
            ],
            "@typescript-eslint/no-shadow": "warn",
            "@typescript-eslint/no-this-alias": "warn",
            "@typescript-eslint/no-unnecessary-boolean-literal-compare": "warn",
            // Null safety for backend operations
            "@typescript-eslint/no-unnecessary-condition": [
                "warn",
                {
                    allowConstantLoopConditions: true, // Allow while(true) patterns in services
                },
            ],
            "@typescript-eslint/no-unnecessary-parameter-property-assignment":
                "warn",
            "@typescript-eslint/no-unnecessary-qualifier": "warn",
            "@typescript-eslint/no-unnecessary-template-expression": "warn",
            "@typescript-eslint/no-unnecessary-type-arguments": "warn",
            // Enhanced type safety for backend services
            "@typescript-eslint/no-unnecessary-type-assertion": "error", // Remove redundant type assertions
            "@typescript-eslint/no-unnecessary-type-constraint": "warn",
            "@typescript-eslint/no-unnecessary-type-conversion": "warn",
            "@typescript-eslint/no-unnecessary-type-parameters": "warn",
            "@typescript-eslint/no-unsafe-argument": "warn", // Warn on passing any to typed parameters
            "@typescript-eslint/no-unsafe-assignment": "warn", // Warn on unsafe assignments to any
            "@typescript-eslint/no-unsafe-call": "warn", // Warn on calling any-typed functions
            "@typescript-eslint/no-unsafe-declaration-merging": "warn",
            "@typescript-eslint/no-unsafe-enum-comparison": "warn",
            "@typescript-eslint/no-unsafe-function-type": "error",
            "@typescript-eslint/no-unsafe-member-access": "warn", // Warn on accessing any-typed properties
            "@typescript-eslint/no-unsafe-return": "warn", // Warn on returning any from typed functions
            "@typescript-eslint/no-unsafe-type-assertion": "warn",
            "@typescript-eslint/no-unsafe-unary-minus": "warn",
            "@typescript-eslint/no-unused-expressions": "warn",
            "@typescript-eslint/no-unused-private-class-members": "warn",
            "@typescript-eslint/no-unused-vars": "warn",
            "@typescript-eslint/no-use-before-define": "warn",
            "@typescript-eslint/no-useless-constructor": "warn",
            "@typescript-eslint/no-useless-empty-export": "warn",
            "@typescript-eslint/no-wrapper-object-types": "error",
            "@typescript-eslint/non-nullable-type-assertion-style": "warn",
            "@typescript-eslint/only-throw-error": "warn",
            "@typescript-eslint/parameter-properties": "warn",
            "@typescript-eslint/prefer-as-const": "warn",
            "@typescript-eslint/prefer-destructuring": "warn",
            "@typescript-eslint/prefer-enum-initializers": "warn",
            "@typescript-eslint/prefer-find": "warn",
            "@typescript-eslint/prefer-for-of": "warn",
            "@typescript-eslint/prefer-function-type": "error",
            "@typescript-eslint/prefer-includes": "warn",
            "@typescript-eslint/prefer-literal-enum-member": "warn",
            "@typescript-eslint/prefer-namespace-keyword": "warn",
            "@typescript-eslint/prefer-nullish-coalescing": [
                "error",
                {
                    ignoreConditionalTests: false, // Check conditionals for nullish coalescing opportunities
                    ignoreMixedLogicalExpressions: false, // Check complex logical expressions
                },
            ],
            "@typescript-eslint/prefer-optional-chain": "error", // Use optional chaining instead of logical AND
            "@typescript-eslint/prefer-promise-reject-errors": "warn",
            // Backend-specific type safety
            "@typescript-eslint/prefer-readonly": "warn", // Prefer readonly for service class properties
            // Keep signal strong on explicitly typed APIs while avoiding noisy
            // churn for inferred callback/test parameters.
            "@typescript-eslint/prefer-readonly-parameter-types": [
                "warn",
                {
                    allow: [
                        {
                            from: "lib",
                            name: ["Readonly"],
                        },
                        {
                            from: "package",
                            name: ["RuleContext", "SourceCode"],
                            package: "@typescript-eslint/utils",
                        },
                        {
                            from: "package",
                            name: [
                                "BinaryExpression",
                                "CallExpression",
                                "Expression",
                                "MemberExpression",
                                "Node",
                                "Program",
                                "Statement",
                                "ThrowStatement",
                                "TSTypeReference",
                                "TSUnionType",
                                "TypeNode",
                            ],
                            package: "@typescript-eslint/types",
                        },
                        {
                            from: "package",
                            name: [
                                "Signature",
                                "Type",
                                "TypeChecker",
                            ],
                            package: "typescript",
                        },
                    ],
                    ignoreInferredTypes: true,
                    treatMethodsAsReadonly: true,
                },
            ],
            "@typescript-eslint/prefer-reduce-type-parameter": "warn",
            "@typescript-eslint/prefer-regexp-exec": "warn",
            "@typescript-eslint/prefer-return-this-type": "warn",
            "@typescript-eslint/prefer-string-starts-ends-with": "warn",
            // Configured: Allows non-async functions that return promises (like utility wrappers around Promise.all)
            // But encourages async for most cases.
            "@typescript-eslint/promise-function-async": [
                "warn",
                {
                    allowAny: true,
                    allowedPromiseNames: ["Promise"],
                    checkArrowFunctions: false,
                },
            ],
            "@typescript-eslint/related-getter-setter-pairs": "warn",
            "@typescript-eslint/require-array-sort-compare": "warn",
            "@typescript-eslint/require-await": "error", // Functions marked async must use await
            "@typescript-eslint/restrict-plus-operands": "warn",
            "@typescript-eslint/restrict-template-expressions": "warn",
            "@typescript-eslint/return-await": ["error", "in-try-catch"], // Proper await handling in try-catch
            "@typescript-eslint/strict-boolean-expressions": "warn",
            "@typescript-eslint/switch-exhaustiveness-check": "error", // Ensure switch statements are exhaustive
            "@typescript-eslint/triple-slash-reference": "warn",
            "@typescript-eslint/unbound-method": "warn",
            "@typescript-eslint/unified-signatures": "warn",
            "@typescript-eslint/use-unknown-in-catch-callback-variable": "warn",
            "canonical/export-specifier-newline": "off",
            "canonical/filename-match-exported": "off",
            "canonical/filename-match-regex": "off", // Taken care of by unicorn rules
            "canonical/filename-no-index": "error",
            "canonical/import-specifier-newline": "off",
            "canonical/no-barrel-import": "error",
            "canonical/no-export-all": "error",
            "canonical/no-import-namespace-destructure": "warn",
            "canonical/no-re-export": "warn",
            "canonical/no-reassign-imports": "error",
            "canonical/no-restricted-imports": "off",
            "canonical/prefer-import-alias": [
                "off",
                {
                    aliases: [
                        {
                            alias: "@plugin/",
                            matchParent: repositoryRootPath,
                            matchPath: "^plugin/",
                            maxRelativeDepth: 0,
                        },
                    ],
                },
            ],
            "canonical/prefer-inline-type-import": "off",
            "canonical/prefer-react-lazy": "off",
            "canonical/prefer-use-mount": "warn",
            "canonical/sort-react-dependencies": "warn",
            "comment-length/limit-multi-line-comments": [
                "warn",
                {
                    ignoreCommentsWithCode: false,
                    ignoreUrls: true,
                    logicalWrap: true,
                    maxLength: 120,
                    mode: "compact-on-overflow",
                    semanticComments: [
                        "@abstract",
                        "@async",
                        "@author",
                        "@callback",
                        "@constructs",
                        "@deprecated",
                        "@emits",
                        "@event",
                        "@example",
                        "@fires",
                        "@generator",
                        "@internal",
                        "@link",
                        "@listens",
                        "@memberof",
                        "@mixes",
                        "@mixin",
                        "@module",
                        "@namespace",
                        "@override",
                        "@packageDocumentation",
                        "@param",
                        "@private",
                        "@protected",
                        "@public",
                        "@readonly",
                        "@remarks",
                        "@returns",
                        "@see",
                        "@since",
                        "@template",
                        "@typeParam",
                        "@typedef",
                        "@version",
                        "@virtual",
                        "@yields",
                        "*`*",
                    ],
                    tabSize: 4,
                },
            ],
            "comment-length/limit-single-line-comments": [
                "warn",
                {
                    ignoreCommentsWithCode: false,
                    ignoreUrls: true,
                    logicalWrap: true,
                    maxLength: 120,
                    mode: "compact-on-overflow",
                    semanticComments: [
                        "@abstract",
                        "@async",
                        "@author",
                        "@callback",
                        "@constructs",
                        "@deprecated",
                        "@emits",
                        "@event",
                        "@example",
                        "@fires",
                        "@generator",
                        "@internal",
                        "@link",
                        "@listens",
                        "@memberof",
                        "@mixes",
                        "@mixin",
                        "@module",
                        "@namespace",
                        "@override",
                        "@packageDocumentation",
                        "@param",
                        "@private",
                        "@protected",
                        "@public",
                        "@readonly",
                        "@remarks",
                        "@returns",
                        "@see",
                        "@since",
                        "@template",
                        "@typeParam",
                        "@typedef",
                        "@version",
                        "@virtual",
                        "@yields",
                        "*`*",
                    ],
                    tabSize: 4,
                },
            ],
            "comment-length/limit-tagged-template-literal-comments": [
                "warn",
                {
                    ignoreCommentsWithCode: false,
                    ignoreUrls: true,
                    logicalWrap: true,
                    maxLength: 120,
                    mode: "compact-on-overflow",
                    semanticComments: [
                        "@abstract",
                        "@async",
                        "@author",
                        "@callback",
                        "@constructs",
                        "@deprecated",
                        "@emits",
                        "@event",
                        "@example",
                        "@fires",
                        "@generator",
                        "@internal",
                        "@link",
                        "@listens",
                        "@memberof",
                        "@mixes",
                        "@mixin",
                        "@module",
                        "@namespace",
                        "@override",
                        "@packageDocumentation",
                        "@param",
                        "@private",
                        "@protected",
                        "@public",
                        "@readonly",
                        "@remarks",
                        "@returns",
                        "@see",
                        "@since",
                        "@template",
                        "@typeParam",
                        "@typedef",
                        "@version",
                        "@virtual",
                        "@yields",
                        "*`*",
                    ],
                    tabSize: 4,
                },
            ],
            // Needs update for Eslint v10
            // "deprecation/deprecation": "off",
            "eslint-plugin/consistent-output": "error",
            "eslint-plugin/fixer-return": "error",
            "eslint-plugin/meta-property-ordering": [
                "error",
                [
                    "defaultOptions",
                    "deprecated",
                    "docs",
                    "fixable",
                    "hasSuggestions",
                    "messages",
                    "replacedBy",
                    "schema",
                    "type",
                ],
            ],
            "eslint-plugin/no-deprecated-context-methods": "error",
            "eslint-plugin/no-deprecated-report-api": "error",
            "eslint-plugin/no-identical-tests": "error",
            "eslint-plugin/no-matching-violation-suggest-message-ids": "error",
            "eslint-plugin/no-meta-replaced-by": "error",
            "eslint-plugin/no-meta-schema-default": "error",
            "eslint-plugin/no-missing-message-ids": "error",
            "eslint-plugin/no-missing-placeholders": "error",
            "eslint-plugin/no-only-tests": "error",
            "eslint-plugin/no-property-in-node": "error",
            "eslint-plugin/no-unused-message-ids": "error",
            "eslint-plugin/no-unused-placeholders": "error",
            "eslint-plugin/no-useless-token-range": "error",
            "eslint-plugin/prefer-message-ids": "error",
            "eslint-plugin/prefer-object-rule": "error",
            "eslint-plugin/prefer-output-null": "error",
            "eslint-plugin/prefer-placeholders": "warn",
            "eslint-plugin/prefer-replace-text": "error",
            "eslint-plugin/report-message-format": "warn",
            "eslint-plugin/require-meta-default-options": "error",
            "eslint-plugin/require-meta-docs-description": "warn",
            "eslint-plugin/require-meta-docs-recommended": "warn",
            "eslint-plugin/require-meta-docs-url": "error",
            "eslint-plugin/require-meta-fixable": "error",
            "eslint-plugin/require-meta-has-suggestions": "error",
            "eslint-plugin/require-meta-schema": "error",
            "eslint-plugin/require-meta-schema-description": "error",
            "eslint-plugin/require-meta-type": "error",
            "eslint-plugin/require-test-case-name": "warn",
            "eslint-plugin/test-case-property-ordering": "warn",
            "eslint-plugin/test-case-shorthand-strings": "error",
            "eslint-plugin/unique-test-case-names": "error",
            "import-x/consistent-type-specifier-style": "off",
            "import-x/default": "warn",
            "import-x/dynamic-import-chunkname": "off",
            "import-x/export": "warn",
            "import-x/exports-last": "off",
            "import-x/extensions": "warn",
            "import-x/first": "warn",
            "import-x/group-exports": "off",
            "import-x/max-dependencies": "off",
            "import-x/named": "warn",
            "import-x/namespace": "warn",
            "import-x/newline-after-import": "warn",
            "import-x/no-absolute-path": "warn",
            "import-x/no-amd": "warn",
            "import-x/no-anonymous-default-export": "warn",
            "import-x/no-commonjs": "warn",
            "import-x/no-cycle": "warn",
            "import-x/no-default-export": "off",
            "import-x/no-deprecated": "warn",
            "import-x/no-duplicates": "warn",
            "import-x/no-dynamic-require": "warn",
            "import-x/no-empty-named-blocks": "warn",
            "import-x/no-extraneous-dependencies": "warn",
            "import-x/no-import-module-exports": "warn",
            "import-x/no-internal-modules": "off",
            "import-x/no-mutable-exports": "warn",
            "import-x/no-named-as-default": "off",
            "import-x/no-named-as-default-member": "off",
            "import-x/no-named-default": "warn",
            "import-x/no-named-export": "off",
            "import-x/no-namespace": "off",
            "import-x/no-nodejs-modules": "off",
            "import-x/no-relative-packages": "warn",
            "import-x/no-relative-parent-imports": "off",
            "import-x/no-rename-default": "warn",
            "import-x/no-restricted-paths": "warn",
            "import-x/no-self-import": "warn",
            "import-x/no-unassigned-import": [
                "error",
                {
                    allow: ["**/*.css", "**/*.scss"], // Allow CSS imports without assignment
                },
            ],
            "import-x/no-unresolved": "off",
            "import-x/no-unused-modules": [
                "warn",
                {
                    missingExports: true,
                    suppressMissingFileEnumeratorAPIWarning: true,
                },
            ],
            "import-x/no-useless-path-segments": "warn",
            "import-x/no-webpack-loader-syntax": "warn",
            "import-x/order": "off",
            "import-x/prefer-default-export": "off",
            "import-x/prefer-namespace-import": "off",
            // NOTE(ESLint10): Re-enable once import-x/unambiguous is
            // compatible with ESLint 10 parser context assumptions.
            "import-x/unambiguous": "off",
            "jsdoc/require-description": "warn",
            "jsdoc/require-param-description": "warn",
            "jsdoc/require-returns-description": "warn",
            "math/abs": "warn",
            "math/prefer-exponentiation-operator": "warn",
            "math/prefer-math-sum-precise": "warn",
            "module-interop/no-import-cjs": "warn",
            "module-interop/no-require-esm": "warn",
            "n/file-extension-in-import": "off",
            "n/no-missing-file-extension": "off",
            "n/no-missing-import": "off",
            // NOTE(ESLint10): Re-enable once eslint-plugin-no-lookahead-lookbehind-regexp supports
            // ESLint 10 without legacy context helpers.
            "no-lookahead-lookbehind-regexp/no-lookahead-lookbehind-regexp":
                "off",
            "perfectionist/sort-arrays": [
                "off",
                {
                    customGroups: [],
                    fallbackSort: { type: "unsorted" },
                    groups: ["literal"],
                    ignoreCase: true,
                    newlinesBetween: "ignore",
                    newlinesInside: "ignore",
                    order: "asc",
                    partitionByNewLine: false,
                    specialCharacters: "keep",
                    type: "natural",
                    useConfigurationIf: {
                        matchesAstSelector: "TSAsExpression > ArrayExpression",
                    },
                },
            ],
            "promise/no-multiple-resolved": "warn",
            "promise/prefer-await-to-callbacks": "off",
            "promise/prefer-await-to-then": "warn",
            "promise/prefer-catch": "warn",
            "promise/spec-only": "warn",
            "sdl/no-nonnull-assertion-on-security-input": "error",
            "sdl/no-trusted-types-policy-pass-through": "error",
            "sdl/no-unsafe-cast-to-trusted-types": "error",
            "security/detect-non-literal-fs-filename": "off",
            "security/detect-object-injection": "off",
            "unused-imports/no-unused-imports": "error",
            "unused-imports/no-unused-vars": "error",
        },
    },
    {
        files: [
            "commitlint.config.mjs",
            "eslint.config.mjs",
            "eslint/config/**/*.{js,mjs,cjs,ts,mts,cts,tsx}",
            "src/**/*.{js,mjs,cjs,ts,mts,cts,tsx}",
            "eslint/config/**/*.{js,mjs,cjs,ts,mts,cts,tsx}",
            "vite.config.ts",
        ],
        name: "ESLint Plugin Source - internal rule authoring overrides",
        rules: {
            "@typescript-eslint/ban-ts-comment": "off",
            "@typescript-eslint/consistent-type-definitions": "off",
            "@typescript-eslint/explicit-function-return-type": "off",
            "@typescript-eslint/explicit-module-boundary-types": "off",
            "@typescript-eslint/no-misused-spread": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-enum-comparison": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unsafe-type-assertion": "off",
            "@typescript-eslint/prefer-destructuring": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            camelcase: "off",
            canonical: "off",
            "canonical/destructuring-property-newline": "off",
            "canonical/id-match": "off",
            "capitalized-comments": [
                "error",
                "always",
                {
                    ignoreConsecutiveComments: true,
                    ignoreInlineComments: true,
                    ignorePattern:
                        "pragma|ignored|import|prettier|eslint|tslint|copyright|license|eslint-disable|@ts-.*|jsx-a11y.*|@eslint.*|global|jsx|jsdoc|prettier|istanbul|jcoreio|metamask|microsoft|no-unsafe-optional-chaining|no-unnecessary-type-assertion|no-non-null-asserted-optional-chain|no-non-null-asserted-nullish-coalescing|@typescript-eslint.*|@docusaurus.*|@react.*|boundaries.*|depend.*|deprecation.*|etc.*|ex.*|functional.*|import-x.*|import-zod.*|jsx-a11y.*|loadable-imports.*|math.*|n.*|neverthrow.*|no-constructor-bind.*|no-explicit-type-exports.*|no-function-declare-after-return.*|no-lookahead-lookbehind-regexp.*|no-secrets.*|no-unary-plus.*|no-unawaited-dot-catch-throw.*|no-unsanitized.*|no-use-extend-native.*|observers.*|prefer-arrow.*|perfectionist.*|prettier.*|promise.*|react.*|react-hooks.*|react-hooks-addons.*|redos.*|regexp.*|require-jsdoc.*|safe-jsx.*|security.*|sonarjs.*|sort-class-members.*|sort-destructure-keys.*|sort-keys-fix.*|sql-template.*|ssr-friendly.*|styled-components-a11y.*|switch-case.*|total-functions.*|tsdoc.*|unicorn.*|unused-imports.*|usememo-recommendations.*|validate-jsx-nesting.*|write-good-comments.*|xss.*|v8.*|c8.*|istanbul.*|nyc.*|codecov.*|coveralls.*|c8-coverage.*|codecov-coverage.*",
                },
            ],
            "class-methods-use-this": "off",
            complexity: "off",
            "consistent-return": "off",
            "dot-notation": "off",
            "func-style": "off",
            "id-length": "off",
            "import-x/extensions": "off",
            "import-x/no-commonjs": "off",
            "import-x/no-rename-default": "off",
            "init-declarations": "off",
            "jsdoc/require-description": "off",
            "jsdoc/require-param-description": "off",
            "jsdoc/require-returns-description": "off",
            "max-classes-per-file": "off",
            "max-lines": "off",
            "max-lines-per-function": "off",
            "max-params": "off",
            "max-statements": "off",
            "module-interop/no-import-cjs": "off",
            "n/no-extraneous-import": "off",
            "n/no-mixed-requires": "off",
            "n/no-sync": "off",
            "n/no-unsupported-features/node-builtins": "off",
            "new-cap": "off",
            "no-console": "off",
            "no-continue": "off",
            "no-inline-comments": "off",
            "no-magic-numbers": "off",
            "no-plusplus": "off",
            "no-ternary": "off",
            "no-undef-init": "off",
            "no-undefined": "off",
            "no-underscore-dangle": "off",
            "no-use-before-define": "off",
            "no-void": "off",
            "object-shorthand": "off",
            "one-var": "off",
            "prefer-arrow-callback": [
                "warn",
                { allowNamedFunctions: true, allowUnboundThis: true },
            ],
            "prefer-destructuring": "off",
            "regexp/require-unicode-regexp": "off",
            "regexp/require-unicode-sets-regexp": "off",
            "require-await": "off",
            "require-unicode-regexp": "off",
            "security/detect-non-literal-fs-filename": "off",
            "security/detect-object-injection": "off",
            "sonarjs/cognitive-complexity": "off",
            "sonarjs/different-types-comparison": "off",
            "sonarjs/no-commented-code": "off",
            "sonarjs/no-nested-conditional": "off",
            "sort-imports": "off",
            "sort-keys": "off",
            "sort-vars": "off",
            "unicorn/consistent-destructuring": "off",
            "unicorn/consistent-function-scoping": "off",
            "unicorn/import-style": "off",
            "unicorn/no-nested-ternary": "off",
            "unicorn/no-null": "off",
            "unicorn/prefer-import-meta-properties": "off",
            "unicorn/prevent-abbreviations": "off",
        },
    },
    // #endregion
];
