import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    docs: [
        {
            id: "intro",
            label: "👋 Welcome",
            type: "doc",
        },
        {
            label: "🧑‍💻 Developer",
            link: {
                id: "developer/index",
                type: "doc",
            },
            items: [
                {
                    id: "developer/release-workflow",
                    label: "🚀 Release Workflow",
                    type: "doc",
                },
                {
                    id: "developer/cli-debugging-and-print-config",
                    label: "🧪 CLI Debugging",
                    type: "doc",
                },
                {
                    id: "developer/docusaurus-site-contract",
                    label: "🧭 Docs & API Workflow",
                    type: "doc",
                },
            ],
            type: "category",
        },
        {
            label: "📘 API Reference",
            items: [
                {
                    dirName: "developer/api",
                    type: "autogenerated",
                },
            ],
            type: "category",
        },
    ],
};

export default sidebars;
