# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Git Leaks Scan

run-name: ${{ format('Gitleaks scan for {0}', github.ref_name) }}

on:
    pull_request:
        branches: ["master"]
        types: [opened, synchronize, reopened, ready_for_review]
    merge_group:
        types: [checks_requested]
    push:
    workflow_dispatch:
    schedule:
        - cron: "12 4 * * *"

concurrency:
    group: gitleaks-${{ github.ref }}
    cancel-in-progress: true

jobs:
    scan:
        name: Gitleaks scan
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
            contents: read
        steps:
            - name: Harden runner
              uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
              with:
                  egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0

            - name: Run Gitleaks
              uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITLEAKS_CONFIG: .gitleaks.toml
